//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Application1 {
    using System;
    using System.Windows;
    using System.Windows.Controls;
    
    
    public class Example : System.Windows.Controls.FlowPanel {
        
        private System.Windows.Controls.TextPanel TextArea;
        
        
        #line 8 "example.xaml"
        
        void handleClick(Element el, ClickEventArgs args) {
            TextArea.Nodes.Add("Button clicked");
        }
        
        #line default
        
        public Example() {
            this.__Initialize_This();
        }
        
        private void __Initialize_This() {
            System.Windows.Controls.FlowPanel _FlowPanel_1_ = this;
            _FlowPanel_1_.SetValue(System.Windows.ArrangedElement.BackgroundProperty, System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.Windows.Media.Paint)).ConvertFromString("LightBlue"));
            System.Windows.Controls.Button _Button_2_ = new System.Windows.Controls.Button();
            _Button_2_.SetValue(System.Windows.BoxedElement.HeightProperty, System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.Windows.BoxUnit)).ConvertFromString("100px"));
            _Button_2_.AddHandler(System.Windows.Controls.ButtonBase.ClickEvent, new System.Windows.Controls.ClickEventHandler(this.handleClick), EventStage.Bubble, EventHandled.Unhandled, true);
            _FlowPanel_1_.Elements.Add(_Button_2_);
            _Button_2_.Nodes.Add("Clicky");
            System.Windows.Controls.TextPanel _TextPanel_3_ = new System.Windows.Controls.TextPanel();
            _TextPanel_3_.SetValue(System.Windows.ArrangedElement.ForegroundProperty, System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.Windows.Media.Paint)).ConvertFromString("White"));
            _TextPanel_3_.SetValue(System.Windows.ArrangedElement.FontFamilyProperty, "Trebuchet MS");
            _TextPanel_3_.SetValue(System.Windows.ArrangedElement.FontSizeProperty, System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.Windows.BoxUnit)).ConvertFromString("72pt"));
            this.TextArea = _TextPanel_3_;
            _TextPanel_3_.SetValue(System.Windows.Element.IDProperty, "TextArea");
            _FlowPanel_1_.Elements.Add(_TextPanel_3_);
            _TextPanel_3_.Nodes.Add("Hello, world!");
        }
    }
}
